### ISSUE TITLE
Segfault en lançant text.out

### ISSUE THREAD

**Issue by VLanvin** [ogaml/ogaml#13]
Je me suis pris une segmentation fault en lançant text.out (après 2-3 secondes d'écran noir, probablement le temps que la font charge).
Ca n'est arrivé que la première fois, maintenant tout fonctionne bien. 
Je n'ai aucune idée d'où ça peut venir, mais j'ouvre une issue pour qu'on s'en souvienne...

**Comment by VLanvin** [comment]
L'appel successif à `X11.Display.create ()`, `X11.VisualInfo.choose` et à `XCreateSimpleWindow` semble suffisant pour provoquer la segfault environ 1 fois sur 5.
Backtrace gdb:

Program received signal SIGSEGV, Segmentation fault.
0x000000000044914d in mark_slice ()
(gdb) bt
#0  0x000000000044914d in mark_slice ()
#1  0x0000000000449a79 in caml_finish_major_cycle ()
#2  0x0000000000456bd3 in caml_compact_heap_maybe ()
#3  0x0000000000449a31 in caml_major_collection_slice ()
#4  0x000000000044a16d in caml_minor_collection ()
#5  0x000000000044a366 in caml_check_urgent_gc ()
#6  0x000000000044dd2b in caml_make_vect ()
#7  0x00000000004076c4 in camlSegfault__aux_1061 () at examples/segfault.ml:17
#8  0x00000000004076e5 in camlSegfault__aux_1061 () at examples/segfault.ml:18
#9  0x00000000004076e5 in camlSegfault__aux_1061 () at examples/segfault.ml:18
#10 0x00000000004076e5 in camlSegfault__aux_1061 () at examples/segfault.ml:18
#11 0x00000000004076e5 in camlSegfault__aux_1061 () at examples/segfault.ml:18
#12 0x0000000000407930 in camlSegfault__entry () at examples/segfault.ml:26
#13 0x0000000000404e69 in caml_program ()
#14 0x00000000004580a6 in caml_start_program ()
#15 0x0000000000000000 in ?? ()
